In [761]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sbn

In [762]:
data = pd.read_csv("OdevTenis.csv")
data

outlook  temperature  humidity  windy play
0      sunny           85        85  False   no
1      sunny           80        90   True   no
2   overcast           83        86  False  yes
3      rainy           70        96  False  yes
4      rainy           68        80  False  yes
5      rainy           65        70   True   no
6   overcast           64        65   True  yes
7      sunny           72        95  False   no
8      sunny           69        70  False  yes
9      rainy           75        80  False  yes
10     sunny           75        70   True  yes
11  overcast           72        90   True  yes
12  overcast           81        75  False  yes
13     rainy           71        91   True   no

In [763]:
""" JUST FOR TYR  """

' JUST FOR TYR  '

In [764]:
#from sklearn.impute import SimpleImputer

In [765]:
#imputer = SimpleImputer(missing_values=np.nan, strategy="mean")

In [766]:
"""yas = data.iloc[:,1:4].values
print(yas)"""

'yas = data.iloc[:,1:4].values\nprint(yas)'

In [767]:
# relocate nan values with mean(average)

"""imputer = imputer.fit(yas[:,1:4])
yas[:,1:4] = imputer.transform(yas[:,1:4])
print(yas)"""

'imputer = imputer.fit(yas[:,1:4])\nyas[:,1:4] = imputer.transform(yas[:,1:4])\nprint(yas)'

In [768]:
outlook = data.iloc[:,0:1].values

In [769]:
outlook

array([['sunny'],
       ['sunny'],
       ['overcast'],
       ['rainy'],
       ['rainy'],
       ['rainy'],
       ['overcast'],
       ['sunny'],
       ['sunny'],
       ['rainy'],
       ['sunny'],
       ['overcast'],
       ['overcast'],
       ['rainy']], dtype=object)

In [770]:
from sklearn import preprocessing

In [771]:
le = preprocessing.LabelEncoder()

In [772]:
"""    ALL OF THEM ( LABEL ENCODER )  IN ONE LINE """
TRY = data.apply(le.fit_transform)
TRY.head(3)

outlook  temperature  humidity  windy  play
0        2           11         4      0     0
1        2            8         6      1     0
2        0           10         5      0     1

In [773]:
outlook[:,0] = le.fit_transform(outlook[:,0])
outlook

array([[2],
       [2],
       [0],
       [1],
       [1],
       [1],
       [0],
       [2],
       [2],
       [1],
       [2],
       [0],
       [0],
       [1]], dtype=object)

In [774]:
ohe = preprocessing.OneHotEncoder()
outlook = ohe.fit_transform(outlook).toarray()

In [775]:
"""     one hot encoder in one line just for try    """
"""ohe.fit(TRY)
OneHotLabels = ohe.transform(TRY).toarray()
OneHotLabels"""

'ohe.fit(TRY)\nOneHotLabels = ohe.transform(TRY).toarray()\nOneHotLabels'

In [776]:
# from kategoric to numeric data
outlook

array([[0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [777]:
sonuc1 = pd.DataFrame(data=outlook, index=range(14), columns=["overcast","rainy","sunny"])

In [778]:
sonuc1

overcast  rainy  sunny
0        0.0    0.0    1.0
1        0.0    0.0    1.0
2        1.0    0.0    0.0
3        0.0    1.0    0.0
4        0.0    1.0    0.0
5        0.0    1.0    0.0
6        1.0    0.0    0.0
7        0.0    0.0    1.0
8        0.0    0.0    1.0
9        0.0    1.0    0.0
10       0.0    0.0    1.0
11       1.0    0.0    0.0
12       1.0    0.0    0.0
13       0.0    1.0    0.0

In [779]:
windy = data.iloc[:,3:4].values
newW = le.fit_transform(data.iloc[:,3:4])
newW = pd.DataFrame(data=newW, index=range(14), columns=["pred WINDY"])
newW

C:\Users\Dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


pred WINDY
0            0
1            1
2            0
3            0
4            0
5            1
6            1
7            0
8            0
9            0
10           1
11           1
12           0
13           1

In [780]:
ohe.fit(windy)
windy = ohe.fit_transform(windy).toarray()
windy

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.]])

In [781]:
sonuc3 = pd.DataFrame(data=windy, index = range(14), columns = ["False","True"])

In [782]:
sonuc3

False  True
0     1.0   0.0
1     0.0   1.0
2     1.0   0.0
3     1.0   0.0
4     1.0   0.0
5     0.0   1.0
6     0.0   1.0
7     1.0   0.0
8     1.0   0.0
9     1.0   0.0
10    0.0   1.0
11    0.0   1.0
12    1.0   0.0
13    0.0   1.0

In [783]:
play = data.iloc[:,-1].values
#play = le.fit_transform(play)
play = np.array(play).reshape((14,1))

In [784]:
# one hot encoder for play=y
y = ohe.fit_transform(play).toarray()
y

array([[1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.]])

In [785]:
sonuc4 = pd.DataFrame(data=y, index = range(14), columns= ["no","yes"])

In [786]:
SAME = pd.DataFrame(data=data.iloc[:,1:3].values, index = range(14), columns= ["TEMP","HUM"])
s = pd.concat([sonuc1,SAME], axis=1)
s

overcast  rainy  sunny  TEMP  HUM
0        0.0    0.0    1.0    85   85
1        0.0    0.0    1.0    80   90
2        1.0    0.0    0.0    83   86
3        0.0    1.0    0.0    70   96
4        0.0    1.0    0.0    68   80
5        0.0    1.0    0.0    65   70
6        1.0    0.0    0.0    64   65
7        0.0    0.0    1.0    72   95
8        0.0    0.0    1.0    69   70
9        0.0    1.0    0.0    75   80
10       0.0    0.0    1.0    75   70
11       1.0    0.0    0.0    72   90
12       1.0    0.0    0.0    81   75
13       0.0    1.0    0.0    71   91

In [787]:
data

outlook  temperature  humidity  windy play
0      sunny           85        85  False   no
1      sunny           80        90   True   no
2   overcast           83        86  False  yes
3      rainy           70        96  False  yes
4      rainy           68        80  False  yes
5      rainy           65        70   True   no
6   overcast           64        65   True  yes
7      sunny           72        95  False   no
8      sunny           69        70  False  yes
9      rainy           75        80  False  yes
10     sunny           75        70   True  yes
11  overcast           72        90   True  yes
12  overcast           81        75  False  yes
13     rainy           71        91   True   no

In [788]:
X = pd.concat([s, sonuc4], axis=1)

In [789]:
X

overcast  rainy  sunny  TEMP  HUM   no  yes
0        0.0    0.0    1.0    85   85  1.0  0.0
1        0.0    0.0    1.0    80   90  1.0  0.0
2        1.0    0.0    0.0    83   86  0.0  1.0
3        0.0    1.0    0.0    70   96  0.0  1.0
4        0.0    1.0    0.0    68   80  0.0  1.0
5        0.0    1.0    0.0    65   70  1.0  0.0
6        1.0    0.0    0.0    64   65  0.0  1.0
7        0.0    0.0    1.0    72   95  1.0  0.0
8        0.0    0.0    1.0    69   70  0.0  1.0
9        0.0    1.0    0.0    75   80  0.0  1.0
10       0.0    0.0    1.0    75   70  0.0  1.0
11       1.0    0.0    0.0    72   90  0.0  1.0
12       1.0    0.0    0.0    81   75  0.0  1.0
13       0.0    1.0    0.0    71   91  1.0  0.0

In [790]:
from sklearn.model_selection import train_test_split

In [791]:
X_train, X_test, y_train, y_test = train_test_split(X,newW, test_size=0.3, random_state=0)

In [792]:
X_train

overcast  rainy  sunny  TEMP  HUM   no  yes
13       0.0    1.0    0.0    71   91  1.0  0.0
9        0.0    1.0    0.0    75   80  0.0  1.0
1        0.0    0.0    1.0    80   90  1.0  0.0
7        0.0    0.0    1.0    72   95  1.0  0.0
10       0.0    0.0    1.0    75   70  0.0  1.0
3        0.0    1.0    0.0    70   96  0.0  1.0
0        0.0    0.0    1.0    85   85  1.0  0.0
5        0.0    1.0    0.0    65   70  1.0  0.0
12       1.0    0.0    0.0    81   75  0.0  1.0

In [793]:
from sklearn.preprocessing import StandardScaler

In [794]:
sc = StandardScaler()

In [795]:
#X_train = sc.fit_transform(X_train)
#X_test = sc.fit_transform(X_test)

## prediction

In [796]:
#dataa = pd.read_csv("satislar.csv")

In [797]:
#dataa.head(10)

In [798]:
#X = dataa[["Aylar"]].values
#y = dataa[["Satislar"]].values

In [799]:
#X

In [800]:
#from sklearn.model_selection import train_test_split

In [801]:
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=0)

In [802]:
#from sklearn.preprocessing import StandardScaler

In [803]:
#ss = StandardScaler()

In [804]:
#X_train = ss.fit_transform(X_train)
#X_test = ss.fit_transform(X_test)
#y_train = ss.fit_transform(y_train)
#y_test = ss.fit_transform(y_test)

In [805]:
# X_train

In [806]:
#X_test

In [807]:
X_train, X_test, y_train, y_test = train_test_split(X,newW, test_size=0.3, random_state=0)


### without scaling we can keep going from here

In [808]:
from sklearn.linear_model import LinearRegression

In [809]:
lr = LinearRegression()

In [810]:
lr.fit(X_train,y_train)

LinearRegression()

In [811]:
ypred = lr.predict(X_test)

In [812]:
ypred

array([[ 0.81859355],
       [ 0.66768067],
       [ 0.47574694],
       [-0.15824585],
       [-0.32625468]])

In [813]:
y_test

pred WINDY
8            0
6            1
4            0
11           1
2            0

In [814]:
new1 = pd.concat([sonuc1, SAME], axis= 1)
new1

overcast  rainy  sunny  TEMP  HUM
0        0.0    0.0    1.0    85   85
1        0.0    0.0    1.0    80   90
2        1.0    0.0    0.0    83   86
3        0.0    1.0    0.0    70   96
4        0.0    1.0    0.0    68   80
5        0.0    1.0    0.0    65   70
6        1.0    0.0    0.0    64   65
7        0.0    0.0    1.0    72   95
8        0.0    0.0    1.0    69   70
9        0.0    1.0    0.0    75   80
10       0.0    0.0    1.0    75   70
11       1.0    0.0    0.0    72   90
12       1.0    0.0    0.0    81   75
13       0.0    1.0    0.0    71   91

In [816]:
"""
new2 = pd.concat([new1, y], axis=1)
new2"""

'\nnew2 = pd.concat([new1, y], axis=1)\nnew2'

In [817]:
"""boy = s2.iloc[:,3:4].values
sol = s2.iloc[:,:3]
sag = s2.iloc[:,4:]
veri = pd.concat([sol,sag], axis=1)"""

'boy = s2.iloc[:,3:4].values\nsol = s2.iloc[:,:3]\nsag = s2.iloc[:,4:]\nveri = pd.concat([sol,sag], axis=1)'

In [819]:
X_train

overcast  rainy  sunny  TEMP  HUM   no  yes
13       0.0    1.0    0.0    71   91  1.0  0.0
9        0.0    1.0    0.0    75   80  0.0  1.0
1        0.0    0.0    1.0    80   90  1.0  0.0
7        0.0    0.0    1.0    72   95  1.0  0.0
10       0.0    0.0    1.0    75   70  0.0  1.0
3        0.0    1.0    0.0    70   96  0.0  1.0
0        0.0    0.0    1.0    85   85  1.0  0.0
5        0.0    1.0    0.0    65   70  1.0  0.0
12       1.0    0.0    0.0    81   75  0.0  1.0

In [820]:
r2 = LinearRegression()
r2.fit(X_train, y_train)

LinearRegression()

In [821]:
ypred = r2.predict(X_test)

In [822]:
ypred

array([[ 0.81859355],
       [ 0.66768067],
       [ 0.47574694],
       [-0.15824585],
       [-0.32625468]])

In [823]:
"""neden = y_test.copy()
neden"""

'neden = y_test.copy()\nneden'

In [824]:
y_test

pred WINDY
8            0
6            1
4            0
11           1
2            0

In [825]:
import statsmodels.api as sm

In [826]:
X = np.append(arr = np.ones((22,1)).astype(int), values=veri, axis=1)
X

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 22 and the array at index 1 has size 14

In [ ]:
xl = veri.iloc[:,[0,1,2,3,4,5]].values
xl = np.array(xl, dtype=float)
model = sm.OLS(boy,xl).fit()
# istatiksel deger olusturmak OLS

In [ ]:
model.summary()

In [ ]:
xl = veri.iloc[:,[0,1,2,3,5]].values
xl = np.array(xl, dtype=float)
model = sm.OLS(boy,xl).fit()

In [ ]:
model.summary()

In [ ]:
xl = veri.iloc[:,[0,1,2,3]].values
xl = np.array(xl, dtype=float)
model = sm.OLS(boy,xl).fit()

In [ ]:
model.summary()